//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRIMServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://health.gov.au")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.UpdateRecordRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.GetRecordRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.RemoveRecordRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.ListRecordsRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.CreateContainerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.GetContainerRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.CreateRecordRequest))]
    public partial class RequestBase : object
    {
        
        private string ProgramNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ProgramName
        {
            get
            {
                return this.ProgramNameField;
            }
            set
            {
                this.ProgramNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRecordRequest", Namespace="http://health.gov.au")]
    public partial class UpdateRecordRequest : TRIMServiceReference.RequestBase
    {
        
        private long RecordUriField;
        
        private string SubProgramNameField;
        
        private string OwnerIdField;
        
        private string OwnerTypeField;
        
        private string ContentField;
        
        private string FileNameField;
        
        private string FileExtensionField;
        
        private System.Nullable<System.DateTime> CreatedTimestampField;
        
        private string ContactIdField;
        
        private string ContactTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubProgramName
        {
            get
            {
                return this.SubProgramNameField;
            }
            set
            {
                this.SubProgramNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string OwnerType
        {
            get
            {
                return this.OwnerTypeField;
            }
            set
            {
                this.OwnerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> CreatedTimestamp
        {
            get
            {
                return this.CreatedTimestampField;
            }
            set
            {
                this.CreatedTimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ContactId
        {
            get
            {
                return this.ContactIdField;
            }
            set
            {
                this.ContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ContactType
        {
            get
            {
                return this.ContactTypeField;
            }
            set
            {
                this.ContactTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRecordRequest", Namespace="http://health.gov.au")]
    public partial class GetRecordRequest : TRIMServiceReference.RequestBase
    {
        
        private System.Nullable<long> RecordUriField;
        
        private string RecordNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveRecordRequest", Namespace="http://health.gov.au")]
    public partial class RemoveRecordRequest : TRIMServiceReference.RequestBase
    {
        
        private System.Nullable<long> RecordUriField;
        
        private string RecordNumberField;
        
        private string ReasonField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Reason
        {
            get
            {
                return this.ReasonField;
            }
            set
            {
                this.ReasonField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRecordsRequest", Namespace="http://health.gov.au")]
    public partial class ListRecordsRequest : TRIMServiceReference.RequestBase
    {
        
        private string OwnerIdField;
        
        private string OwnerTypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string OwnerType
        {
            get
            {
                return this.OwnerTypeField;
            }
            set
            {
                this.OwnerTypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateContainerRequest", Namespace="http://health.gov.au")]
    public partial class CreateContainerRequest : TRIMServiceReference.RequestBase
    {
        
        private string FreeTextTitleField;
        
        private string ClassificationField;
        
        private string TemplateRecordNumberField;
        
        private System.Nullable<long> OwnerUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FreeTextTitle
        {
            get
            {
                return this.FreeTextTitleField;
            }
            set
            {
                this.FreeTextTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Classification
        {
            get
            {
                return this.ClassificationField;
            }
            set
            {
                this.ClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string TemplateRecordNumber
        {
            get
            {
                return this.TemplateRecordNumberField;
            }
            set
            {
                this.TemplateRecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<long> OwnerUri
        {
            get
            {
                return this.OwnerUriField;
            }
            set
            {
                this.OwnerUriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContainerRequest", Namespace="http://health.gov.au")]
    public partial class GetContainerRequest : TRIMServiceReference.RequestBase
    {
        
        private System.Nullable<long> RecordUriField;
        
        private string RecordNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateRecordRequest", Namespace="http://health.gov.au")]
    public partial class CreateRecordRequest : TRIMServiceReference.RequestBase
    {
        
        private string SubProgramNameField;
        
        private string ContainerClassificationField;
        
        private string OwnerIdField;
        
        private string OwnerTypeField;
        
        private string ContainerRecordNumberField;
        
        private string ContentField;
        
        private string FileNameField;
        
        private string FileExtensionField;
        
        private System.DateTime CreatedTimestampField;
        
        private string ContactIdField;
        
        private string ContactTypeField;
        
        private System.Nullable<long> OwnerUriField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubProgramName
        {
            get
            {
                return this.SubProgramNameField;
            }
            set
            {
                this.SubProgramNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string ContainerClassification
        {
            get
            {
                return this.ContainerClassificationField;
            }
            set
            {
                this.ContainerClassificationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string OwnerType
        {
            get
            {
                return this.OwnerTypeField;
            }
            set
            {
                this.OwnerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ContainerRecordNumber
        {
            get
            {
                return this.ContainerRecordNumberField;
            }
            set
            {
                this.ContainerRecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public string FileExtension
        {
            get
            {
                return this.FileExtensionField;
            }
            set
            {
                this.FileExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.DateTime CreatedTimestamp
        {
            get
            {
                return this.CreatedTimestampField;
            }
            set
            {
                this.CreatedTimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ContactId
        {
            get
            {
                return this.ContactIdField;
            }
            set
            {
                this.ContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ContactType
        {
            get
            {
                return this.ContactTypeField;
            }
            set
            {
                this.ContactTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public System.Nullable<long> OwnerUri
        {
            get
            {
                return this.OwnerUriField;
            }
            set
            {
                this.OwnerUriField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProcessResult", Namespace="http://health.gov.au")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.GetRecordResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.RemoveRecordResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.ListRecordsResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.CreateContainerResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.GetContainerResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.UpdateRecordResult))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(TRIMServiceReference.CreateRecordResult))]
    public partial class ProcessResult : object
    {
        
        private TRIMServiceReference.TransactionStatus TransactionStatusField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TRIMServiceReference.TransactionStatus TransactionStatus
        {
            get
            {
                return this.TransactionStatusField;
            }
            set
            {
                this.TransactionStatusField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatus", Namespace="http://health.gov.au")]
    public partial class TransactionStatus : object
    {
        
        private TRIMServiceReference.TransactionStatusCode TransactionStatusCodeField;
        
        private TRIMServiceReference.Message[] MessagesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TRIMServiceReference.TransactionStatusCode TransactionStatusCode
        {
            get
            {
                return this.TransactionStatusCodeField;
            }
            set
            {
                this.TransactionStatusCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public TRIMServiceReference.Message[] Messages
        {
            get
            {
                return this.MessagesField;
            }
            set
            {
                this.MessagesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetRecordResult", Namespace="http://health.gov.au")]
    public partial class GetRecordResult : TRIMServiceReference.ProcessResult
    {
        
        private long RecordUriField;
        
        private string RecordNumberField;
        
        private string OwnerIdField;
        
        private string OwnerTypeField;
        
        private string ContentField;
        
        private string NameField;
        
        private string ExtensionField;
        
        private long FileSizeField;
        
        private string ContactIdField;
        
        private string ContactTypeField;
        
        private string ContainerRecordNumberField;
        
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string OwnerId
        {
            get
            {
                return this.OwnerIdField;
            }
            set
            {
                this.OwnerIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string OwnerType
        {
            get
            {
                return this.OwnerTypeField;
            }
            set
            {
                this.OwnerTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Content
        {
            get
            {
                return this.ContentField;
            }
            set
            {
                this.ContentField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public long FileSize
        {
            get
            {
                return this.FileSizeField;
            }
            set
            {
                this.FileSizeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ContactId
        {
            get
            {
                return this.ContactIdField;
            }
            set
            {
                this.ContactIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string ContactType
        {
            get
            {
                return this.ContactTypeField;
            }
            set
            {
                this.ContactTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public string ContainerRecordNumber
        {
            get
            {
                return this.ContainerRecordNumberField;
            }
            set
            {
                this.ContainerRecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=11)]
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.CreatedDateTimeField;
            }
            set
            {
                this.CreatedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RemoveRecordResult", Namespace="http://health.gov.au")]
    public partial class RemoveRecordResult : TRIMServiceReference.ProcessResult
    {
        
        private long RecordUriField;
        
        private string RecordNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRecordsResult", Namespace="http://health.gov.au")]
    public partial class ListRecordsResult : TRIMServiceReference.ProcessResult
    {
        
        private TRIMServiceReference.RecordList RecordListField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public TRIMServiceReference.RecordList RecordList
        {
            get
            {
                return this.RecordListField;
            }
            set
            {
                this.RecordListField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateContainerResult", Namespace="http://health.gov.au")]
    public partial class CreateContainerResult : TRIMServiceReference.ProcessResult
    {
        
        private long RecordUriField;
        
        private string RecordNumberField;
        
        private string TitleField;
        
        private string FreeTextTitleField;
        
        private long OwnerUriField;
        
        private string StructuredTitleField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string FreeTextTitle
        {
            get
            {
                return this.FreeTextTitleField;
            }
            set
            {
                this.FreeTextTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public long OwnerUri
        {
            get
            {
                return this.OwnerUriField;
            }
            set
            {
                this.OwnerUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public string StructuredTitle
        {
            get
            {
                return this.StructuredTitleField;
            }
            set
            {
                this.StructuredTitleField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetContainerResult", Namespace="http://health.gov.au")]
    public partial class GetContainerResult : TRIMServiceReference.ProcessResult
    {
        
        private long RecordUriField;
        
        private string RecordNumberField;
        
        private string TitleField;
        
        private string FreeTextTitleField;
        
        private string StructuredTitleField;
        
        private long OwnerUriField;
        
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public string FreeTextTitle
        {
            get
            {
                return this.FreeTextTitleField;
            }
            set
            {
                this.FreeTextTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public string StructuredTitle
        {
            get
            {
                return this.StructuredTitleField;
            }
            set
            {
                this.StructuredTitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public long OwnerUri
        {
            get
            {
                return this.OwnerUriField;
            }
            set
            {
                this.OwnerUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.DateTime CreatedDateTime
        {
            get
            {
                return this.CreatedDateTimeField;
            }
            set
            {
                this.CreatedDateTimeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateRecordResult", Namespace="http://schemas.datacontract.org/2004/07/HPCMAttachmentsService.WCFServices.Struct" +
        "ures.DataContracts.Record")]
    public partial class UpdateRecordResult : TRIMServiceReference.ProcessResult
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CreateRecordResult", Namespace="http://health.gov.au")]
    public partial class CreateRecordResult : TRIMServiceReference.ProcessResult
    {
        
        private long RecordUriField;
        
        private string RecordNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string RecordNumber
        {
            get
            {
                return this.RecordNumberField;
            }
            set
            {
                this.RecordNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransactionStatusCode", Namespace="http://health.gov.au")]
    public enum TransactionStatusCode : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Success = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Failed = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://health.gov.au")]
    public partial class Message : object
    {
        
        private int MessageIdField;
        
        private string MessageDescriptionField;
        
        private TRIMServiceReference.MessageLevel MessageLevelField;
        
        private string MessageLongDescriptionField;
        
        private string ScreenFieldNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string MessageDescription
        {
            get
            {
                return this.MessageDescriptionField;
            }
            set
            {
                this.MessageDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public TRIMServiceReference.MessageLevel MessageLevel
        {
            get
            {
                return this.MessageLevelField;
            }
            set
            {
                this.MessageLevelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string MessageLongDescription
        {
            get
            {
                return this.MessageLongDescriptionField;
            }
            set
            {
                this.MessageLongDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string ScreenFieldName
        {
            get
            {
                return this.ScreenFieldNameField;
            }
            set
            {
                this.ScreenFieldNameField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageLevel", Namespace="http://health.gov.au")]
    public enum MessageLevel : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debug = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Information = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="RecordList", Namespace="http://health.gov.au", ItemName="RecordListItem")]
    public class RecordList : System.Collections.Generic.List<TRIMServiceReference.ListRecordsStruct>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListRecordsStruct", Namespace="http://health.gov.au")]
    public partial class ListRecordsStruct : object
    {
        
        private long RecordUriField;
        
        private string NameField;
        
        private string ExtensionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long RecordUri
        {
            get
            {
                return this.RecordUriField;
            }
            set
            {
                this.RecordUriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string Extension
        {
            get
            {
                return this.ExtensionField;
            }
            set
            {
                this.ExtensionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://health.gov.au", ConfigurationName="TRIMServiceReference.HPCMAttachmentsService")]
    public interface HPCMAttachmentsService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/CreateRecord", ReplyAction="http://health.gov.au/HPCMAttachmentsService/CreateRecordResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.CreateRecordResponse> CreateRecordAsync(TRIMServiceReference.CreateRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/UpdateRecord", ReplyAction="http://health.gov.au/HPCMAttachmentsService/UpdateRecordResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.UpdateRecordResponse> UpdateRecordAsync(TRIMServiceReference.UpdateRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/GetRecord", ReplyAction="http://health.gov.au/HPCMAttachmentsService/GetRecordResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.GetRecordResponse> GetRecordAsync(TRIMServiceReference.GetRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/RemoveRecord", ReplyAction="http://health.gov.au/HPCMAttachmentsService/RemoveRecordResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.RemoveRecordResponse> RemoveRecordAsync(TRIMServiceReference.RemoveRecordRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/ListRecords", ReplyAction="http://health.gov.au/HPCMAttachmentsService/ListRecordsResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.ListRecordsResponse> ListRecordsAsync(TRIMServiceReference.ListRecordsRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/CreateContainer", ReplyAction="http://health.gov.au/HPCMAttachmentsService/CreateContainerResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.CreateContainerResponse> CreateContainerAsync(TRIMServiceReference.CreateContainerRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://health.gov.au/HPCMAttachmentsService/GetContainer", ReplyAction="http://health.gov.au/HPCMAttachmentsService/GetContainerResponse")]
        System.Threading.Tasks.Task<TRIMServiceReference.GetContainerResponse> GetContainerAsync(TRIMServiceReference.GetContainerRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRecord", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class CreateRecordRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.CreateRecordRequest request;
        
        public CreateRecordRequest1()
        {
        }
        
        public CreateRecordRequest1(TRIMServiceReference.CreateRecordRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateRecordResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class CreateRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.CreateRecordResult CreateRecordResult;
        
        public CreateRecordResponse()
        {
        }
        
        public CreateRecordResponse(TRIMServiceReference.CreateRecordResult CreateRecordResult)
        {
            this.CreateRecordResult = CreateRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRecord", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class UpdateRecordRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.UpdateRecordRequest request;
        
        public UpdateRecordRequest1()
        {
        }
        
        public UpdateRecordRequest1(TRIMServiceReference.UpdateRecordRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="UpdateRecordResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class UpdateRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.UpdateRecordResult UpdateRecordResult;
        
        public UpdateRecordResponse()
        {
        }
        
        public UpdateRecordResponse(TRIMServiceReference.UpdateRecordResult UpdateRecordResult)
        {
            this.UpdateRecordResult = UpdateRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecord", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class GetRecordRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.GetRecordRequest request;
        
        public GetRecordRequest1()
        {
        }
        
        public GetRecordRequest1(TRIMServiceReference.GetRecordRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetRecordResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class GetRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.GetRecordResult GetRecordResult;
        
        public GetRecordResponse()
        {
        }
        
        public GetRecordResponse(TRIMServiceReference.GetRecordResult GetRecordResult)
        {
            this.GetRecordResult = GetRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRecord", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class RemoveRecordRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.RemoveRecordRequest request;
        
        public RemoveRecordRequest1()
        {
        }
        
        public RemoveRecordRequest1(TRIMServiceReference.RemoveRecordRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RemoveRecordResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class RemoveRecordResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.RemoveRecordResult RemoveRecordResult;
        
        public RemoveRecordResponse()
        {
        }
        
        public RemoveRecordResponse(TRIMServiceReference.RemoveRecordResult RemoveRecordResult)
        {
            this.RemoveRecordResult = RemoveRecordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListRecords", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class ListRecordsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.ListRecordsRequest request;
        
        public ListRecordsRequest1()
        {
        }
        
        public ListRecordsRequest1(TRIMServiceReference.ListRecordsRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ListRecordsResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class ListRecordsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.ListRecordsResult ListRecordsResult;
        
        public ListRecordsResponse()
        {
        }
        
        public ListRecordsResponse(TRIMServiceReference.ListRecordsResult ListRecordsResult)
        {
            this.ListRecordsResult = ListRecordsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateContainer", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class CreateContainerRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.CreateContainerRequest request;
        
        public CreateContainerRequest1()
        {
        }
        
        public CreateContainerRequest1(TRIMServiceReference.CreateContainerRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="CreateContainerResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class CreateContainerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.CreateContainerResult CreateContainerResult;
        
        public CreateContainerResponse()
        {
        }
        
        public CreateContainerResponse(TRIMServiceReference.CreateContainerResult CreateContainerResult)
        {
            this.CreateContainerResult = CreateContainerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContainer", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class GetContainerRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.GetContainerRequest request;
        
        public GetContainerRequest1()
        {
        }
        
        public GetContainerRequest1(TRIMServiceReference.GetContainerRequest request)
        {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContainerResponse", WrapperNamespace="http://health.gov.au", IsWrapped=true)]
    public partial class GetContainerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://health.gov.au", Order=0)]
        public TRIMServiceReference.GetContainerResult GetContainerResult;
        
        public GetContainerResponse()
        {
        }
        
        public GetContainerResponse(TRIMServiceReference.GetContainerResult GetContainerResult)
        {
            this.GetContainerResult = GetContainerResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface HPCMAttachmentsServiceChannel : TRIMServiceReference.HPCMAttachmentsService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class HPCMAttachmentsServiceClient : System.ServiceModel.ClientBase<TRIMServiceReference.HPCMAttachmentsService>, TRIMServiceReference.HPCMAttachmentsService
    {
        
        public HPCMAttachmentsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.CreateRecordResponse> CreateRecordAsync(TRIMServiceReference.CreateRecordRequest1 request)
        {
            return base.Channel.CreateRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.UpdateRecordResponse> UpdateRecordAsync(TRIMServiceReference.UpdateRecordRequest1 request)
        {
            return base.Channel.UpdateRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.GetRecordResponse> GetRecordAsync(TRIMServiceReference.GetRecordRequest1 request)
        {
            return base.Channel.GetRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.RemoveRecordResponse> RemoveRecordAsync(TRIMServiceReference.RemoveRecordRequest1 request)
        {
            return base.Channel.RemoveRecordAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.ListRecordsResponse> ListRecordsAsync(TRIMServiceReference.ListRecordsRequest1 request)
        {
            return base.Channel.ListRecordsAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.CreateContainerResponse> CreateContainerAsync(TRIMServiceReference.CreateContainerRequest1 request)
        {
            return base.Channel.CreateContainerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TRIMServiceReference.GetContainerResponse> GetContainerAsync(TRIMServiceReference.GetContainerRequest1 request)
        {
            return base.Channel.GetContainerAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
    }
}
